### ISSUE TITLE
Submission gallyavm sumanth0703

### ISSUE THREAD

**Issue by sumanth0703** [Simulation-Software-Engineering/git-exercise#13]
https://github.com/Holy-Commas/git-exercise

**Comment by uekerman** [comment]
Looks OK :+1:

A few suggestions for improvement:

* You ended up with two commits named "Duplication has been removed by defining a new function inin" -> not ideal
* For future exercises (we will need this again), please be aware that there is a difference between forking and importing a project.
* If you close a pull request, always write and explain why.
* Don't add temporary files, such as `.idea` to version control. A ''.gitignore'' file can help preventing this.

Task 3A)

`tolerance` is no default argument in your code. Solution would be:

```python
    def contains(self, point: Point2D, tolerance=0.0) -> bool:
```
