### ISSUE TITLE
Submission proelstl kurtyisn

### ISSUE THREAD

**Issue by Till223** [Simulation-Software-Engineering/git-exercise#14]
https://github.com/SSR-Apfel/git-exercise

**Comment by uekerman** [comment]
Looks good :+1:

Good commit messages are very important to allow others to follow your project. Don't write "Task2 b" and "implement" does typically not say much. Commit messages should reflect the what and ideally the why. "Created helper function _is_within_interval to remove duplicate in function contains" is better.

Task 1A)

Fix the problem, don't fake the test :grin: 

```python
def __init__(self, coordinates: List[float]) -> None:
        self._coordinates = coordinates.copy()
```
