### ISSUE TITLE
Submission tarpansa cevikma

### ISSUE THREAD

**Issue by senatirpan** [Simulation-Software-Engineering/git-exercise#15]
https://github.com/SimulationSE-exercise/git-exercise-1

**Comment by uekerman** [comment]
Looks good :+1:

* For future exercises (we will need this again), please be aware that there is a difference between forking and importing a project. You also forked the wrong repo :grin: (and did the extra exercise 4)

Test 3A)

The "interval check" should test an interval, so 1D data, e.g.

```python
def num_in_interval(num: float, left_fence: float, right_fence: float) -> bool:
    return left_fence <= num <= right_fence
```
