### ISSUE TITLE
Submission aburabazam Kujoen 

### ISSUE THREAD

**Issue by aburabazam** [Simulation-Software-Engineering/git-exercise#16]
https://github.com/SSE-Exercise-Group/git-exercise

**Comment by Kujoen** [comment]
Nice !

**Comment by uekerman** [comment]
Looks good :+1:

Also try to give good names to pull requests, just as for commits.

Task 3A)

```python
def is_within_interval(x: int, interval: int, tolerance: float):
    return x >= - tolerance and x <= interval + tolerance
```

... is not ideal. `x` and `interval` should probably be floats? And an interval normally has a lower and an upper border "[a,b]".
