### ISSUE TITLE
Submission sulaimyr marquaml

### ISSUE THREAD

**Issue by mardom1** [Simulation-Software-Engineering/git-exercise#2]
https://github.com/BlaBlaBla2022/git-exercise

**Comment by uekerman** [comment]
Looks good :+1: 
Always try to write good commit messages. "Ex 2 task b" is not so good, "Add test for vector subtraction" is better.

Task 1a)

It's better to add the copy to the constructor:

```python
def __init__(self, coordinates: List[float]) -> None:
    self._coordinates = coordinates.copy()
```

Task 3a)

```python
def _is_in_interval(self, i: int, end: int, tolerance: float) -> bool:
        return i >= -tolerance and i <= end + tolerance
```
`i` and `end` should be floats as well, no?
