### ISSUE TITLE
Submission 991jo bluzukk 

### ISSUE THREAD

**Issue by bluzukk** [Simulation-Software-Engineering/git-exercise#3]
[https://github.com/SSE-Exercise-2022/git-exercise](https://github.com/SSE-Exercise-2022/git-exercise)

**Comment by 991jo** [comment]
quick correction: the gitlab useraccounts are erwerljs and hofmanjn

**Comment by uekerman** [comment]
Looks good :+1:

Task 3a)

It's a bit odd to define the function `_is_in_interval` within another function. Conceptually, you could even define it outside of `Rectangle`.
