### ISSUE TITLE
Submission aroravi attilaks

### ISSUE THREAD

**Issue by kis-balazs** [Simulation-Software-Engineering/git-exercise#5]
https://github.com/SSE-Group2/git-exercise

**Comment by uekerman** [comment]
Looks OK :+1:

Commit messages should always reflect what you did and why. We will do many commits this semester. Please keep in mind. 

Citing from the worksheet:

> and use appropriate commit messages (not Solve task A).


Task 1A)

Fix the problem, don't fake the test :grin: 

```python
def __init__(self, coordinates: List[float]) -> None:
        self._coordinates = coordinates.copy()
```

**Comment by kis-balazs** [comment]
Oh so very sorry! :D Got lost inbetween instructions 🗡️
