### ISSUE TITLE
Submission bhawsina mananijh

### ISSUE THREAD

**Issue by CodyGirl** [Simulation-Software-Engineering/git-exercise#6]
https://github.com/SSE-Practice/git-exercise

**Comment by uekerman** [comment]
Looks good :+1:

Try to use meaningful commit messages. "Ex 1 task B" is not so good, "added tolerance argument to contains" is better.
Commit messages should reflect the what and ideally the why.

Task 1A)

Fix the problem, don't fake the test :grin: 

```python
def __init__(self, coordinates: List[float]) -> None:
        self._coordinates = coordinates.copy()
```
