### ISSUE TITLE
Submission  github exercise ahmedmd youssemk parajuba

### ISSUE THREAD

**Issue by MohamedAdelNaguib** [Simulation-Software-Engineering/git-exercise#9]
https://github.com/SIMBADABU/git-exercise

**Comment by uekerman** [comment]
OK enough :+1:, but a few things to learn:


* Don't add files like `__pycache__` or `.DS_Store` to version control. A `.gitignore` file can help preventing this.
* Commit messages should reflect the what and ideally the why. Don't use "Ex2 task a".
* If you close pull requests, always write why.
* Tests for exercise 1 and 3 fail:

Task 1A)

```python
def __init__(self, coordinates: List[float]) -> None:
        self._coordinates = coordinates.copy()
```

Task 1B)

You have to delete

https://github.com/SIMBADABU/git-exercise/blob/5a12756ba6def1b2a110542976b237e98c4a0f5d/exercise1.py#L55

It's bad practice to add commented-out code (especially without writing why it is commented out):

https://github.com/SIMBADABU/git-exercise/blob/5a12756ba6def1b2a110542976b237e98c4a0f5d/exercise2.py#L10

Task 3A)

You could simplify this code:

https://github.com/SIMBADABU/git-exercise/blob/5a12756ba6def1b2a110542976b237e98c4a0f5d/exercise3.py#L29-L32

Task 3C)

https://github.com/SIMBADABU/git-exercise/blob/5a12756ba6def1b2a110542976b237e98c4a0f5d/exercise3.py#L34

You could directly pass `0.0` as default value:

```python
def contains(self, point: Point2D, tolerance=0.0) -> bool:
```
